- id: aidbox
  logo: aidbox
  title: Aidbox
  icon: aidbox
  icon-type: hs
  type: Commercial
  major: true
  abstract:
    ru: Облачная платформа для создания медицинских систем на основе HL7® FHIR®.
    en: FHIR platform for modern web and mobile healthcare applications.
  description:
    ru: >-
      Aidbox - это платформа, предоставляемая в качестве услуги (PaaS) для разработки медицинских
      решений на основе HL7® FHIR®.
      Aidbox подходит для построения мобильных и веб-решений, оперирующих
      медицинскими данными: электронные персональные медицинские записи (EHR), интеграционные "шины",
      репозитории медицинских данных (реестры), госпитальные информационные системы (HIS),
      порталы для пациентов и телемедицины.
    en: >-
      Aidbox is a platform for modern web and mobile healthcare applications built on top of a centralized FHIR server.<br>
      Business applications of Aidbox:
      <ul>
      <li>Aidbox as a Back­end. Aidbox can dramatically decrease "time to market" for new health IT products by providing "out of the box" backbone features and continuous delivery pipeline.</li>
      <li>Aidbox as a Clinical Data Repository. Aidbox can aggregate and normalize data (FHIR Information Model) from different sources and provides powerful tools like PostgreSQL, ElasticSearch, druid.io for Data Analytic & Decision Support services.</li>
      <li>Aidbox as an API Facade. Aidbox could be connected to existing systems (EHR, EMR, LIS, RIS etc) and provides standard FHIR REST & WebSocket API for development and hosting of portable Single Page and Smart on FHIR Applications (ONC certified API that satisfies MU Stage 3 requirements).</li>
      <li>Aidbox as an Integration Bus. Aidbox can help to connect systems by flexible connectors for popular protocols (HL7v2, CDA/CCD, FHIR, custom) and REST, Messaging and Publish/Subscribe communication patterns.</li>
      </ul><br>
      Anyone can register at <a href="https://aidbox.io">aidbox.io</a> and make their own testing/evaluation of aidbox platform absolutely free. Aidbox can be deployed into any infrastructure of customer's choice (linux servers in the cloud or private data center).
  features:
    ru:
      - Использует Fhirbase для хранения данных
      - Реализует REST API на основе стандарта HL7® FHIR®
      - Решает вопросы безопасности с помощью использования OAuth2
      - Предоставляет хостинг для базы и несложных одностраничных приложений (SPA)
      - Предоставляет SDK и возможность интегрироваться с решениями на ваших технологиях (Java, .Net и т. д.)
    en:
      - Based on the FHIR (Fast Healthcare Interoperability Resources) standard for external & internal data information model, aidbox implements generic FHIR server specification (tested in project Argonaut and featured in one of HSPC HIMSS 2016 demonstrations)
      - Aidbox provides relational storage for FHIR resources with use of open source fhirbase project (that gives scalability and power of rich SQL language)
      - Data aggregation by widespread legacy HL7 v2 messaging, CDA/CCD documents, FHIR REST API and custom processable data channels
      - Aidbox ensures security. OAuth 2.0 provider, policy­based Access Control, complete audit of any events in system
      - SDK for all features, based on reference FHIR clients for popular platforms (Java, .NET, JavaScript, Objective­C, Ruby, Python and iOS)
      - Implements FHIR terminology server specification and provide LOINC, Snomed, RxNorm, ICD­10, CPT, FHIR terminologies out of the box
      - Implements FHIR terminology server specification and provide LOINC, Snomed, RxNorm, ICD­10, CPT, FHIR terminologies out of the box
      - Compatible with SMART on FHIR interface and could host SPA web applications (JavaScript, HTML5, CSS3)
      - Aidbox provides analytics tools based on PostgreSQL, Elasticsearch and Druid OLAP
      - Automated cloud infrastructure. It could be hosted in public and private clouds, with automatic failover, backups and updates
      - Aidbox provides foundation for workflow support with use of queues, customizable providers and consumers
  links: 
    direct: https://aidbox.io/
  tags:
    - Amazon AWS
    - Fhirbase
    - Clojure
    - AngularJS
- id: fhirbase
  logo: fhirbase
  title: Fhirbase
  icon: fhirbase
  icon-type: svg
  type: Open-source
  abstract:
    ru: Реляционное хранилище медицинских данных на основе стандарта HL7® FHIR®.
    en: Enterprise grade relational storage for FHIR resources.
  description: 
    ru: >-
      Fhirbase - это реляционное хранилище со встроенной моделью данных,
      соответствующей международному стандарту HL7® FHIR®. Fhirbase подходит для
      построения медицинских информационных системы разных классов: электронные
      карты (EHR), интеграционные "шины", репозитории медицинских данных
      (реестры), госпитальные системы (HIS), порталы для пациентов и
      телемедицины.
    en: >-
      Fhirbase is a relational storage based on the FHIR (Fast Healthcare Interoperability Resources)
      standard for external & internal data information model. It provides scalability, power of rich 
      SQL language and allows you to use a technology of your choice.<br><br>
      Fhirbase got a significant traction among medical technology companies, provider organizations and pharma.
  features:
    ru:
      - Построен на PostgreSQL с использованием языка plv8
      - Реализует модель данных соответствующую стандарту HL7® FHIR®
      - Имеет простой REST API для обращения к данным
    en:
      - Simple SQL API similar to FHIR REST
      - CRUD (create, read, update and delete) for FHIR resources
      - History for FHIR resources
      - Transactions
      - Search
      - Terminology and value sets
  links:
    direct: http://fhirbase.github.io/
    github: https://github.com/fhirbase
    chat: https://groups.google.com/forum/#!forum/fhirbase
  tags:
    - PostgreSQL
    - plv8
    - HL7® FHIR®
- id: fhir-js
  icon: fhir-js
  icon-type: hs
  title: FHIR.js
  type: Open-source
  abstract:
    ru: Референсная реализация FHIR клиента на JavaScript. Эта библиотека разработана совместно с SMART Platform.
    en: Reference implementation of the FHIR client in JavaScript. This library is used in Aidbox and SMART Platforms. 
  description: 
    ru: >-
      Упрощает получение FHIR-данных в JavaScript-приложениях, написанных на
      Node.js, AngularJS, jQuery или YUI. Реализует привычный синтаксис и
      архитектуру. FHIR.js - библиотека универсальных JavaScript-адаптеров для
      получения данных FHIR-сервера.
    en: >-
      FHIR.js facilitates working with FHIR servers in JavaScript applications developed with use of Node.js, 
      AngularJS, jQuery or YUI. It implements familiar syntax and architecture.    
  features:
    ru:
      - Простой и выразительный синтаксис запросов
      - Поддерживает CRUD операции по стандарту HL7® FHIR®
      - Поддерживает базовую HTTP авторизацию
      - Поддерживает OAuth2 авторизацию
    en:
      - Support of HL7® FHIR® CRUD (create, read, update and delete) operations
      - Friendly and expressive query syntax
      - Support for adapters that provide idiomatic interfaces in AngularJS, jQuery, YUI, etc
      - Supports HTTP basic and OAuth2 authorization
  links:
    github: https://github.com/FHIR/fhir.js
  tags:
    - JavaScript
    - Node.js
    - YUI
    - jQuery
    - AngularJS
- id: formstamp
  logo: formstamp
  icon: formstamp
  icon-type: hs
  title: FormStamp
  type: Open-source
  abstract:
    ru: FormStamp - это библиотека виджетов на AngularJS для разработки веб-приложений с «богатым» клиентом.
    en: FormStamp is an AngularJS library of widgets for development of rich web applications.
  description: 
    ru: >-
      FormStamp - набор директив AngularJS для быстрого описания и связывания
      форм с данными приложения. Упрощает прототипирование, стилизацию,
      валидацию данных и вывод ошибок.
    en: >-
      FormStamp is a set of AngularJS directives for quick defining and linking forms with application data. It allows to simplify prototyping, stylization, data validation, and output of errors.   
  features:
    ru:
      - Написан на «чистом» AngularJS
      - Имеет встроенный FormBuilder
      - Стилизован на Twitter Bootstrap
      - Имеет минималистичный codebase
    en:
      - Written in "pure" AngularJS
      - Has built-in FormBuilder
      - Utilizes Twitter Bootstrap style
      - Has minimalistic codebase  
  links:
    direct: http://formstamp.github.io/
    github: https://github.com/formstamp/formstamp
    chat: https://gitter.im/formstamp/formstamp
  tags:
    - JavaScript
    - AngularJS
- id: fhir-schema
  logo: 
  title: FHIR-schema
  type: Open-source
  icon: fhir-schema
  abstract: 
  description: 
    ru: >-
      Библиотека для описания профилей (StructureDefinition) FHIR-ресурсов с помощь JSON
      Schema. Привносит лучшие практики для описания и валидации структур данных
      из мира JavaScript в мир FHIR.
    en: >-
      Library for description of FHIR resources StructureDefinitions by means of JSON
      Schema. It introduces best practices of data structure description and validation from JavaScript world into the world of FHIR.
  features:
  links:
    github: https://github.com/fhir-js/fhir-schema
    chat: https://github.com/fhir-js/fhir-schema/blob/master/zulip.fhir.me
  tags:
    - JavaScript
    - JSON
    - HL7® FHIR®
- id: foodtaster
  logo: foodtaster
  title: Foodtaster
  type: Open-source
  icon: foodtaster
  abstract: 
    ru: Библиотека для тестирования Chef конфигурации с помощью RSpec
    en: Library for testing Chef configurations using RSpec
  description: 
    ru: >-
      Foodtaster позволяет разрабатывать сложную серверную инфраструктуру в
      лучших традициях гибких методологий. Помогает системным администраторам и
      DevOps-специалистам автоматизировать проверки межсерверного
      взаимодействия. Foodtaster сближает разработчиков и системных
      администраторов.
    en: >-
      Foodtaster allows to develop complex server infrastructure in the best traditions of 
      agile methodologies. It helps system administrators and DevOps specialists to automate 
       interserver interactions checking. Foodtaster draws together developers and system 
      administrators.
  features:
    ru:
      - Использует Vagrant и виртуальные машины
      - Привносит TDD-подход в конфигурирование инфраструктуры
    en:
      - Utilizes Vagrant and virtual machines
      - Introduces TDD approach into configuring of infrastructure
  links:
    github: https://github.com/mlapshin/foodtaster
  tags:
    - Chef
    - Vagrant
    - RSpec
    - TDD
