- id: bootstrap
  icon: rocket
  title:
    ru: '"Быстрый старт проекта" и обучение вашей команды'
    en: Quick project start and education of your team
  description:
    ru: Развернем наши технологичные продукты и обучим вашу команду для дальнейшей работы.
    en: We will deploy our high-tech health IT products into infrastructure of your choice and educate your team.
  post: 
    ru: >
      У вас есть новый проект, вы не хотите тянуть с выпуском в свет первой версии,
      но в тоже время заложить «правильный фундамент» для дальнейшего развития продукта, 
      используя стандарты, международные наработки и опыт.
    en: >
      You have a new project and you don't want to delay the release of its first version but at the same 
      time you want to lay a "proper foundation" for the further product development with use of 
      international medical standards, ready-to-use components and experience.    
  steps-statement:
    ru: "Мы поможем вам:"
    en: "We will help you:"
  steps:
    ru:
      - >
        Вникнем в идею будущего решения, 
        совместно сформируем Product Vision и очертим границы продукта. 
        Проведем аналитическую работу и построим стартовую модель данных продукта на базе HL7® FHIR®.
      - >
        Развернем и настроим наши технологичные продукты, 
        которые закроют вопросы хранения информации, 
        интеграции с другими системами через FHIR REST API и 
        создадут хороший фундамент для разработки будущего решения.
      - >
        Обучим вашу команду FHIR стандарту, 
        работе с нашими технологичными продуктами и поучаствуем в формировании архитектуры 
        будущего продукта с учетом специфики.
    en:
      - >        
        We will drill down into an idea of your future solution. 
        We will generate a Product Vision and outline the boundaries of your product together.
        We will carry out analytical work and build a starting data model for your product on the base of HL7® FHIR® standard.
      - >
        We will deploy and configure our high-tech health IT products into infrastructure of your choice.
        These products are designed to solve issues with storing of medical information and
        integration of your solution with other medical systems via HL7 v.2, CCD and HL7® FHIR® REST API.
        Our health IT products provide a great foundation for future development.
      - >
        We will educate your team about HL7® FHIR® standard, our health IT products and participate
        in design of your project architecture taking into account its specificity.

- id: development
  icon: rocket
  title:
    ru: '"Быстрый старт проекта" и разработка под заказ'
    en: Quick project start, and custom development 
  description:
    ru: Реализуем ваш проект на базе наших технологичных продуктов.
    en: We will implement your project with use of our health IT products.
  post:
    ru: >
      У вас есть новый проект, вы не хотите тянуть с выпуском в свет первой версии,
      но в тоже время заложить «правильный фундамент» для дальнейшего развития продукта, 
      используя стандарты, международные наработки и опыт.
    en: >
      You have a new project and you don't want to delay the release of its first version but at the same 
      time you want to lay a "proper foundation" for the further product development with use of 
      international medical standards, ready-to-use components and experience.    
  steps-statement:
    ru: "Мы поможем вам:"
    en: "We will help you:"
  steps:
    ru:
      - >
        Вникнем в идею будущего решения, 
        совместно сформируем Product Vision и очертим границы продукта. 
        Проведем аналитическую работу и построим стартовую модель данных продукта на базе HL7® FHIR®.        
      - >
        Развернем и настроим наши технологичные продукты, 
        которые закроют вопросы хранения информации, 
        интеграции с другими системами через FHIR REST API и 
        создадут хороший фундамент для разработки будущего решения.
      - >
        Возьмем на себя разработку вашего решения «под ключ», 
        выделив под проект кроссфункциональную команду профессионалов и выстроив процесс разработки 2-х недельными итрациями, в лучших традициях гибких 
        и бережливых подходов к разработке ПО.
    en:
      - >
        We will drill down into an idea of your future solution. 
        We will generate a Product Vision and outline the boundaries of your product together.
        We will carry out analytical work and build a starting data model for your product on the base of HL7® FHIR® standard.
      - >
        We will deploy and configure our high-tech health IT products into infrastructure of your choice.
        These products are designed to solve issues with storing of medical information and
        integration of your solution with other medical systems via HL7 v.2, CCD and HL7® FHIR® REST API.
        Our health IT products provide a great foundation for future development.
      - >
        We will dedicate a cross-functional team of engineers to your project and will develop your solution on a turnkey basis with
        use of iterative development process in the best traditions of flexible and cost-conscious approaches to software development.

- id: fhirbase-support
  icon: life-ring
  title:
    ru: Коммерческая поддержка для продукта FHIRbase
    en: FHIRbase commercial support
  description:
    ru: 'Доработаем FHIRbase под ваши нужды, выделим специалиста для помощи и подпишем вас на обновления.'
    en: We will modify FHIRbase to suit your needs, dedicate one of our engineers to assist you and sign you up for updates.
  post: 
    ru: >
      Вы используете в своем проекте хранилище с открытым кодом FHIRbase, 
      и у вас появилась потребность доработать этот продукт под специфику проекта. 
      Вы понимаете, что лучше переложить эту работу на плечи идеологов и создателей FHIRbase.
    en: >
      You use open-source storage FHIRbase in your project and have a need to modify it in accordance with the specificity of your project.
      It is better to pass the job to ideologists and creators of FHIRbase.      
  steps-statement:
    ru: "Мы поможем вам:"
    en: "We will help you:"
  steps:
    ru: 
      - Вникнем в ваш проект, обсудим недостающую в FHIRbase функциональность.
      - Оценим трудоемкость, согласуем и заключим с вами договор на доработку FHIRbase под специфику вашего проекта.
      - Доработаем FHIRbase и предоставим вам новую версию, дополненную недостающей функциональностью.
    en: 
      - We will drill down into an idea of your project and discuss deficient functionality of FHIRbase.
      - We will estimate complexity and efforts needed to modigy FHIRbase to fully suit needs of your project.
      - We will modify FHIRbase and provide you with a version complete with functionality that you are missing.  

- id: consulting
  title:
    ru: Консалтинг и аудит  
    en: Consulting & Audit
  icon: binoculars
  description:
    ru:
      'Прочитаем семинары/тренинги по стандарту HL7® FHIR® и нашим
      продуктам, обучим вашу команду.'
    en:
      We offer seminars and trainings abour HL7® FHIR® standard and our
      products. We will train your engineering team.
  post: 
    ru: >
      Вы очень хотите "правильно", но не знаете как. У вас есть сложная задача,
      но у вас не получается ее решить, вы в поиске экспертов в области,
      которые проконсультируют и скажут как сделать правильно.
    en: >
      You really want to "make it right", but you don't know how. You have a complex task,
      but you haven't found a solution. You are looking for experts in the health IT domain,
      which will consult your team and explain "how to make it right" to you.     
  steps-statement:
    ru: "Мы поможем вам:"
    en: "We will help you:"
  steps:
    ru:
      - >
        Поможем сформулировать концепцию решения, выявить требования к вашему продукту
        и построить модель данных для будущего решения на основе стандарта HL7® FHIR®.
      - >
        Поучаствуем в архитектурных сессиях с вашей командой и поможем выработать 
        правильное решение: выбрать стандарт, спроектировать архитектуру. 
      - >
        Подскажем какие международные наработки использовать.
        Сделаем процессный и технический аудит вашего проекта и в результате дадим рекомендации 
        по улучшениям.
    en:
      - >
        We will describe a concept of your solution. We will identify the requirements of your project
        and build a data model for your future solution on the basis of HL7® FHIR® standard.
      - >
        We will collaborate in architectural design sessions with your team and help you to develop
        a good quality solution. We will assist you in choosing standards and designing of the architecture.
      - >
        We will suggest which available SDKs and libraries to use.
        We will make a process and technical audit of your project and provide you with recommendations on improvements.
