- id: bootstrap
  icon: rocket
  title:
    ru: '"Быстрый старт проекта" и обучение вашей команды'
    en: Quick project start and education of your team
  description:
    ru: Развернем наши технологичные продукты и обучим вашу команду для дальнейшей работы.
    en: We will deploy our high-tech products and educate your team for further work.
  post: >
    У вас есть новый проект, вы не хотите тянуть с выпуском в свет первой версии,
    но в тоже время заложить «правильный фундамент» для дальнейшего развития продукта, 
    используя стандарты и международные наработки и опыт.
  steps-statement:
    ru: Мы поможем вам
    en: We will help you
  steps:
    - >
      Вникнем в идею будущего решения, 
      совместно сформируем Product Vision и очертим границы продукта. 
      Проведем аналитическую работу и построим стартовую модель данных продукта на базе HL7® FHIR®.
    - >
      Развернем и настроим наши технологичные продукты, 
      которые закроют вопросы хранения информации, 
      интеграции с другими системами через FHIR REST API и 
      создадут хороший фундамент для разработки будущего решения.
    - >
      Обучим вашу команду FHIR стандарту, 
      работе с нашими технологичными продуктами и поучаствуем в формировании архитектуры 
      будущего продукта с учетом специфики.

  
- id: development
  icon: rocket
  title:
    ru: '"Быстрый старт проекта" и разработка под заказ'
    en: Quick project start, and custom development 
  description:
    ru: Реализуем ваш проект на базе наших технологичных продуктов.
    en: We will realize your project on the basis of our high-tech products
  post: >
    У вас есть новый проект, вы не хотите тянуть с выпуском в свет первой версии,
    но в тоже время заложить «правильный фундамент» для дальнейшего развития продукта, 
    используя стандарты и международные наработки и опыт.
  steps-statement:
    ru: "Мы поможем вам:"
    en: "We will help you:"
  steps:
    ru:
      - >
        Вникнем в идею будущего решения, 
        совместно сформируем Product Vision и очертим границы продукта. 
        Проведем аналитическую работу и построим стартовую модель данных продукта на базе HL7® FHIR®.
      - >
        Развернем и настроим наши технологичные продукты, 
        которые закроют вопросы хранения информации, 
        интеграции с другими системами через FHIR REST API и 
        создадут хороший фундамент для разработки будущего решения.
      - >
        Возьмем на себя разработку вашего решения «под ключ», 
        выделив под проект кроссфункциональную команду профессионалов и выстроив процесс разработки 2-х недельными итрациями, в лучших традициях гибких 
        и бережливых подходов к разработке ПО.
    en:
      - >
        We will drill down into the idea of a future solution, generate Product Vision and outline the boundaries of the product together.
        We will carry out the analytical works and build a starting data model of the product based on the HL7® FHIR®.
      - >
        We will deploy and configure our high-tech products
        which are designed to close questions with storage of information,
        integration with other systems through the HL7® FHIR® REST API, and
        create a good foundation for the future solutions development.
      - >
        We will undertake the development of your solutions on a turnkey basis 
        providing for the project a cross-functional team of professionals, and build
        the process of developing in 2-week iterations in the best tradition of flexible
        and cost-conscious approaches to the software development.

- id: fhirbase-support
  icon: life-ring
  title:
    ru: Коммерческая поддержка для продукта FHIRbase
    en: FHIRbase commercial support
  description:
    ru: 'Доработаем FHIRbase под ваши нужды, выделим специалиста для помощи и подпишем вас на обновления.'
    en: We will modify FHIRbase to suit your needs, provide a specialist to help you and sign you up for updates.
  post: >
      Вы используете в своем проекте хранилище с открытым кодом FHIRbase, 
      и у вас появилась потребность доработать этот продукт по специфику проекта. 
      Вы понимаете, что лучше переложить эту работу на плечи идеологов и создателей FHIRbase.
  steps-statement:
    ru: "Мы поможем вам:"
    en: "We will help you:"
  steps:
    ru: 
      - Вникнем в ваш проект, обсудим недостающую в FHIRbase функциональность.
      - Оценим трудоемкость, согласуем и заключим с вами договор на доработку FHIRbase под специфику вашего проекта.
      - Доработаем FHIRbase и предоставим вам новую версию, дополненную недостающей функциональностью.
    en: 
      - TODO:Вникнем в ваш проект, обсудим недостающую в FHIRbase функциональность.
      - TODO:Оценим трудоемкость, согласуем и заключим с вами договор на доработку FHIRbase под специфику вашего проекта.
      - TODO:Доработаем FHIRbase и предоставим вам новую версию, дополненную недостающей функциональностью.

- id: consulting
  title:
    ru: Консалтинг и аудит  
    en: Consulting & Audit
  icon: binoculars
  description: 'Прочитаем семинары/тренинги по стандарту HL7® FHIR® и нашим продуктам, обучим вашу команду.'
  post: >
      Вы очень хотите "правильно", но не знаете как. У вас есть сложная задача,
      но у вас не получается ее решить, вы в поиске экспертов в области,
      которые проконсультируют и скажут как сделать правильно.
  steps-statement:
    ru: Мы поможем вам
    en: We will help you
  steps:
    ru:
      - >
        Поможем сформулировать концепцию решения, выявить требования к вашему продукту
        и построить модель данных для будущего решения на основе стандарта HL7® FHIR®.
      - >
        Поучаствуем в архитектурных сессиях с вашей командой и поможем выработать 
        правильное решение: выбрать стандарт, спроектировать архитектуру. 
      - >
        Подскажем какие международные наработки использовать.
        Сделаем процессный и технический аудит вашего проекта и в результате дадим рекомендации 
        по улучшениям.
    en:
      - >
        Поможем сформулировать концепцию решения, выявить требования к вашему продукту
        и построить модель данных для будущего решения на основе стандарта HL7® FHIR®.
      - >
        Поучаствуем в архитектурных сессиях с вашей командой и поможем выработать 
        правильное решение: выбрать стандарт, спроектировать архитектуру. 
      - >
        Подскажем какие международные наработки использовать.
        Сделаем процессный и технический аудит вашего проекта и в результате дадим рекомендации 
        по улучшениям.
