- id: bootstrap
  icon: rocket
  title:
    ru: '"Быстрый старт проекта" и обучение вашей команды'
    en: Quick project start and education of your team
  description:
    ru: Развернем наши технологичные продукты и обучим вашу команду для дальнейшей работы.
    en: We will deploy our high-tech products and educate your team for further work.
  post: 
    ru: >
      У вас есть новый проект, вы не хотите тянуть с выпуском в свет первой версии,
      но в тоже время заложить «правильный фундамент» для дальнейшего развития продукта, 
      используя стандарты, международные наработки и опыт.
    en: >
      You have a new project, you don't want to delay the release of the first version, but at the same 
      time you want to lay the "proper foundation" for the further product development, using 
      international standards, groundwork and experience.    
  steps-statement:
    ru: "Мы поможем вам:"
    en: "We will help you:"
  steps:
    ru:
      - >
        Вникнем в идею будущего решения, 
        совместно сформируем Product Vision и очертим границы продукта. 
        Проведем аналитическую работу и построим стартовую модель данных продукта на базе HL7® FHIR®.
      - >
        Развернем и настроим наши технологичные продукты, 
        которые закроют вопросы хранения информации, 
        интеграции с другими системами через FHIR REST API и 
        создадут хороший фундамент для разработки будущего решения.
      - >
        Обучим вашу команду FHIR стандарту, 
        работе с нашими технологичными продуктами и поучаствуем в формировании архитектуры 
        будущего продукта с учетом специфики.
    en:
      - >        
        We will drill down into the idea of a future solution, 
        generate Product Vision and outline the boundaries of the product together.
        We will carry out the analytical work and build a starting data model of the product on the base of HL7® FHIR® standard.
      - >
        We will deploy and configure our high-tech products
        which are designed to close questions with storage of information,
        integration with other systems through the HL7® FHIR® REST API, and
        create a good foundation for the future solutions development.
      - >
        We will educate your team on HL7® FHIR® standard, 
        on how to work with our high-tech products, and participate
        in the formation of architecture of the future product taking into account its specificity.

- id: development
  icon: rocket
  title:
    ru: '"Быстрый старт проекта" и разработка под заказ'
    en: Quick project start, and custom development 
  description:
    ru: Реализуем ваш проект на базе наших технологичных продуктов.
    en: We will implement your project on the basis of our high-tech products
  post:
    ru: >
      У вас есть новый проект, вы не хотите тянуть с выпуском в свет первой версии,
      но в тоже время заложить «правильный фундамент» для дальнейшего развития продукта, 
      используя стандарты, международные наработки и опыт.
    en: >
      You have a new project, you don't want to delay the release of the first version, but at the same 
      time you want to lay the "proper foundation" for the further product development, using 
      international standards, groundwork and experience.
  steps-statement:
    ru: "Мы поможем вам:"
    en: "We will help you:"
  steps:
    ru:
      - >
        Вникнем в идею будущего решения, 
        совместно сформируем Product Vision и очертим границы продукта. 
        Проведем аналитическую работу и построим стартовую модель данных продукта на базе HL7® FHIR®.        
      - >
        Развернем и настроим наши технологичные продукты, 
        которые закроют вопросы хранения информации, 
        интеграции с другими системами через FHIR REST API и 
        создадут хороший фундамент для разработки будущего решения.
      - >
        Возьмем на себя разработку вашего решения «под ключ», 
        выделив под проект кроссфункциональную команду профессионалов и выстроив процесс разработки 2-х недельными итрациями, в лучших традициях гибких 
        и бережливых подходов к разработке ПО.
    en:
      - >
        We will drill down into the idea of a future solution, generate Product Vision and outline the boundaries of the product together.
        We will carry out the analytical work and build a starting data model of the product on the base of HL7® FHIR® standard.
      - >
        We will deploy and configure our high-tech products
        which are designed to close questions with storage of information,
        integration with other systems through the HL7® FHIR® REST API, and
        create a good foundation for the future solutions development.
      - >
        We will undertake the development of your solutions on a turnkey basis 
        providing for the project a cross-functional team of professionals, and build
        the process of developing in 2-week iterations in the best tradition of flexible
        and cost-conscious approaches to the software development.

- id: fhirbase-support
  icon: life-ring
  title:
    ru: Коммерческая поддержка для продукта FHIRbase
    en: FHIRbase commercial support
  description:
    ru: 'Доработаем FHIRbase под ваши нужды, выделим специалиста для помощи и подпишем вас на обновления.'
    en: We will modify FHIRbase to suit your needs, provide a specialist to help you and sign you up for updates.
  post: 
    ru: >
      Вы используете в своем проекте хранилище с открытым кодом FHIRbase, 
      и у вас появилась потребность доработать этот продукт под специфику проекта. 
      Вы понимаете, что лучше переложить эту работу на плечи идеологов и создателей FHIRbase.
    en: >
      You use open-source storage FHIRbase in your project and you have the need to modify 
      the product in accordance with the specifics of your project.
      You understand that it is better to pass the job on the shoulders of the ideologists and creators of FHIRbase.      
  steps-statement:
    ru: "Мы поможем вам:"
    en: "We will help you:"
  steps:
    ru: 
      - Вникнем в ваш проект, обсудим недостающую в FHIRbase функциональность.
      - Оценим трудоемкость, согласуем и заключим с вами договор на доработку FHIRbase под специфику вашего проекта.
      - Доработаем FHIRbase и предоставим вам новую версию, дополненную недостающей функциональностью.
    en: 
      - Drill down into the idea of your future project and discuss deficient functionality of FHIRbase.
      - Estimate the complexity, coordinate and sign a contract with you to refine FHIRbase under the specifics of your project. 
      - Refine FHIRbase and provide you with a new version, complete with the missing functionality.  

- id: consulting
  title:
    ru: Консалтинг и аудит  
    en: Consulting & Audit
  icon: binoculars
  description:
    ru:
      'Прочитаем семинары/тренинги по стандарту HL7® FHIR® и нашим
      продуктам, обучим вашу команду.'
    en:
      We do seminars and trainings on standard HL7® FHIR® and our
      products, we will train your team.
  post: 
    ru: >
      Вы очень хотите "правильно", но не знаете как. У вас есть сложная задача,
      но у вас не получается ее решить, вы в поиске экспертов в области,
      которые проконсультируют и скажут как сделать правильно.
    en: >
      You really want to do it "properly", but don't know how. You have a complex task,
      but you didn't manage to find a solution, and you are looking for experts in the domain,
      who will consult and tell you how to make it right.     
  steps-statement:
    ru: "Мы поможем вам:"
    en: "We will help you:"
  steps:
    ru:
      - >
        Поможем сформулировать концепцию решения, выявить требования к вашему продукту
        и построить модель данных для будущего решения на основе стандарта HL7® FHIR®.
      - >
        Поучаствуем в архитектурных сессиях с вашей командой и поможем выработать 
        правильное решение: выбрать стандарт, спроектировать архитектуру. 
      - >
        Подскажем какие международные наработки использовать.
        Сделаем процессный и технический аудит вашего проекта и в результате дадим рекомендации 
        по улучшениям.
    en:
      - >
        Phrase a solution concept, identify the requirements for your product
        and build a data model for the future solution on the basis of the HL7® FHIR® standard.
      - >
        Collaborate in architectural sessions with your team and help to develop
        the correct solution: choose a standard, design architecture.
      - >
        Suggest which international groundwork to use.
        Make the process and technical audit of your project and, as a result, give you our 
        recommendations on improvements.
