- id: bootstrap
  icon: rocket
  title:
    ru: '"Быстрый старт проекта" и обучение вашей команды'
    en: Quick start
  description:
    ru: Развернем наши технологичные продукты и обучим вашу команду для дальнейшей работы.
    en: ????
  post: >
    У вас есть новый проект, вы не хотите тянуть с выпуском в свет первой версии,
    но в тоже время заложить «правильный фундамент» для дальнейшего развития продукта, 
    используя стандарты и международные наработки и опыт.
  steps-statement:
    ru: Мы поможем вам
    en: We will help you
  steps:
    - >
      Вникнем в идею будущего решения, 
      совместно сформируем Product Vision и очертим границы продукта. 
      Проведем аналитическую работу и построим стартовую модель данных продукта на базе HL7 FHIR.
    - >
      Развернем и настроим наши технологичные продукты, 
      которые закроют вопросы хранения информации, 
      интеграции с другими системами через FHIR REST API и 
      создадут хороший фундамент для разработки будущего решения.
    - >
      Обучим вашу команду FHIR стандарту, 
      работе с нашими технологичными продуктами и поучаствуем в формировании архитектуры 
      будущего продукта с учетом специфики.

  
- id: development
  icon: rocket
  title:
    ru: '"Быстрый старт проекта" и разработка под заказ'
    en: Quick start...
  description:
    ru: Реализуем ваш проект на базе наших технологичных продуктов.
    en: ????
  post: >
    У вас есть новый проект, вы не хотите тянуть с выпуском в свет первой версии,
    но в тоже время заложить «правильный фундамент» для дальнейшего развития продукта, 
    используя стандарты и международные наработки и опыт.
  steps-statement:
    ru: Мы поможем вам
    en: We will help you
  steps:
    ru:
      - >
        Вникнем в идею будущего решения, 
        совместно сформируем Product Vision и очертим границы продукта. 
        Проведем аналитическую работу и построим стартовую модель данных продукта на базе HL7 FHIR.
      - >
        Развернем и настроим наши технологичные продукты, 
        которые закроют вопросы хранения информации, 
        интеграции с другими системами через FHIR REST API и 
        создадут хороший фундамент для разработки будущего решения.
      - >
        Возьмем на себя разработку вашего решения «под ключ», 
        выделив под проект кроссфункциональную команду профессионалов и выстроив процесс разработки 2-х недельными итрациями, в лучших традициях гибких 
        и бережливых подходов к разработке ПО.
    en:
      - >
        TODO:Вникнем в идею будущего решения, 
        совместно сформируем Product Vision и очертим границы продукта. 
        Проведем аналитическую работу и построим стартовую модель данных продукта на базе HL7 FHIR.
      - >
        TODO:Развернем и настроим наши технологичные продукты, 
        которые закроют вопросы хранения информации, 
        интеграции с другими системами через FHIR REST API и 
        создадут хороший фундамент для разработки будущего решения.
      - >
        TODO:Возьмем на себя разработку вашего решения «под ключ», 
        выделив под проект кроссфункциональную команду профессионалов и выстроив процесс разработки 2-х недельными итрациями, в лучших традициях гибких 
        и бережливых подходов к разработке ПО.

- id: fhirbase-support
  icon: life-ring
  title:
    ru: Коммерческая поддержка для продукта Fhirbase,
    en: Fhirbase comercial support
  description:
    ru: 'Доработаем Fhirbase под ваши нужды, выделим специалиста для помощи и подпишем вас на обновления.'
    en: ???
  post: >
      Вы используете в своем проекте хранилище с открытым кодом Fhirbase 
      и у вас появилась потребность доработать этот продукт по специфику проекта. 
      Вы понимаете, что лучше переложить эту работу на плечи идеологов и создателей Fhirbase.
  steps-statement:
    ru: Мы поможем вам
    en: We will help you
  steps:
    ru: 
      - Вникнем в ваш проект, обсудим недостающую в Fhirbase функциональность.
      - Оценим трудоемкость, согласуем и заключим с вами договор на доработку Fhirbase под специфику вашего проекта.
      - Доработаем Fhirbase и предоставим вам новую версию, дополненную недостающей функциональностью.
    en: 
      - TODO:Вникнем в ваш проект, обсудим недостающую в Fhirbase функциональность.
      - TODO:Оценим трудоемкость, согласуем и заключим с вами договор на доработку Fhirbase под специфику вашего проекта.
      - TODO:Доработаем Fhirbase и предоставим вам новую версию, дополненную недостающей функциональностью.

- id: consulting
  title:
    ru: Консалтинг и аудит  
    en: Consulting & Audit
  icon: binoculars
  description: 'Прочитаем семинары/тренинги по FHIR и нашим продуктам, обучим вашу команду.'
  post: >
      Вы очень хотите "правильно", но не знаете как. У вас есть сложная задача,
      но у вас не получается ее решить, вы в поиске экспертов в области,
      которые проконсультируют и скажут как сделать правильно.
  steps-statement:
    ru: Мы поможем вам
    en: We will help you
  steps:
    ru:
      - >
        Поможем сформулировать концепцию решения, выявить требования к вашему продукту
        и построить модель данных для будущего решения на основе стандарта HL7 FHIR.
      - >
        Поучаствуем в архитектурных сессиях с вашей командой и поможем выработать 
        правильное решение: выбрать стандарт, спроектировать архитектуру. 
      - >
        Подскажем какие международные наработки использовать.
        Сделаем процессный и технический аудит вашего проекта и в результате дадим рекомендации 
        по улучшениям.
    en:
      - >
        Поможем сформулировать концепцию решения, выявить требования к вашему продукту
        и построить модель данных для будущего решения на основе стандарта HL7 FHIR.
      - >
        Поучаствуем в архитектурных сессиях с вашей командой и поможем выработать 
        правильное решение: выбрать стандарт, спроектировать архитектуру. 
      - >
        Подскажем какие международные наработки использовать.
        Сделаем процессный и технический аудит вашего проекта и в результате дадим рекомендации 
        по улучшениям.
