- id: fhir-intro
  title:
    ru: Основы FHIR
    en: FHIR intro 
  img: imgs/fhir-intro.svg
  abstract:
    ru: >
      Восьмичасовой семинар по основным особенностям стандарта
      HL7 FHIR и экосистеме вокруг стандарта.
    en: >
      8 hour training about HL7 FHIR standard in Russian
  desc:
    ru: >
      Многие разработчики, приходя в Health IT, часто недооценивают сложность предметной области
      и не знают, с какой стороны подступиться к большому количеству стандартов и спецификаций.
      В этом однодневном тренинге команда HealthSamurai, которая имеет 10-летний опыт
      работы в Health IT и является активным участником организации HL7, постарается дать вам правильный старт.
      Мы кратко ознакомим вас с актуальными стандартами обмена медицинской информацией и их историей.
      Основная часть тренинга будет посвящена молодому, но очень перспективному стандарту HL7® FHIR®,
      который включил в себя основные достижения предшествующих стандартов и исключил многие их недостатки.
    en: >
      Many developers coming to Health IT often underestimate complexity of the domain and don't know from which side to approach the multiple number of standards and specifications. In this one-day training, the HealthSamurai team which has 10 years of experience in Health IT and is an active member of HL7 International, will endeavour to give you the right starting point. We will briefly familiarize you with actual healthcare information exchange standards and their history. The main part of the training will be devoted to the new but very perspective HL7® FHIR® standard which includes principal achievements of previous standards and excludes many of their demerits.
    plan: fhir-intro.ru.md
  tags:
    - FHIR®
    - HL7®
    - HL7® standards
- id: fhirbase
  title:
    en: FHIRbase anatomy
    ru: Анатомия FHIRbase
  abstract:
    ru: >
      Тренинг по архитектуре и использованию открытой медицинской базы данных FHIRbase в разработке
      решений для здравоохранения
    en: >
      Training about the architecture and usage of an open-source healthcare database FHIRbase in development of healthcare solutions
  desc:
    ru: >
      FHIRbase - это база данных, созданная на основе стандарта HL7® FHIR® и открытой реляционной базы данных
      PostgreSQL для хранения медицинской информации. Двухдневный тренинг от разработчиков этой базы
      позволит вам научиться её использовать и разобраться в том, как она устроена. Тренинг не подразумевает
      глубоких познаний в PostgreSQL, основные возможности которого будут объяснены по ходу тренинга.
      Интерфейс FHIRbase прост, но более глубокое понимание её устройства даст
      вам возможность пользоваться всей мощью PostgreSQL и эффективно расширять FHIRbase под ваши
      конкретные нужды. Также мы затронем вопросы практической эксплуатации FHIRbase в боевых условиях,
      такие как настройка производительности, репликация и бэкапы.
    en: >
      FHIRbase is a database created on the base of HL7® FHIR® standard and open relational database PostgreSQL, for 
      the storage of healthcare information. The two-day training from developers of this database, will give you an ability
      to learn how it is organized and how to use it. The training does not imply deep knowledge of PostgreSQL, main 
      features of which will be introduced as the training proceeds. Interface of FHIRbase is simple though keen insight into 
      its structure will allow you to make use of PostgreSQL and extend FHIRbase effectively under your specific needs. Also, 
      we will touch upon a subject of practical usage of FHIRbase in production, such as performance configuration, replicaton
      and backups.
    img: imgs/fhirbase.svg
    plan: fhirbase.ru.md
  tags:
    - FHIR
    - FHIRbase
    - PostgreSQL
- id: devops
  title:
    ru: Непрерывная поставка
    en: Continuous Delivery
  img: imgs/devops.svg
  tags:
    - DevOps
    - ContinuousDelivery
    - LEAN
  abstract:
    ru: Двухдневный тренинг по подходам и инструментам построения непрерывного цикла поставки
    en: Two days training about Continuous Delivery....
  desc: >
    Современный софт стремительно превращается из коробочного продукта в
    сервис. Пользователи хотят получать доступ к новым функциям
    как можно быстрее. Цикл поставки у лидеров рынка сократился до дней
    или даже часов. Поэтому, чтобы выжить, мы должны пересмотреть и перестроить
    процесс производства информационных систем коренным образом, и это непростой
    вызов. Двухдневный тренинг от HealthSamurai возможно станет первым шагом в этом
    направлении. Мы познакомимся с движением DevOps и философией бережливого производства (LEAN).
    Попробуем хорошие практики и инструменты позволяющие выстроить эффективную
    и надежную линию непрерывного производства (Continuous Delivery Pipeline)
  plan: devops.ru.md
