- id: fhir-intro
  title:
    ru: Основы FHIR
    en: FHIR intro 
  img: /imgs/fhir-intro.svg
  abstract:
    ru: >
      Восьмичасовой семинар по основным особенностям стандарта
      HL7 FHIR и экосистеме вокруг стандарта.
    en: >
      8 hour training about HL7 FHIR standard in Russian
  desc: >
    Многие разработчики приходя в Health IT часто не дооценивают сложности предметной области
    и не знают с какой стороны подступиться к большому колличеству стандартов и спецификаций.
    В этом однодневном тренинге, команда HealthSamurai, которая имеет 10 летний опыт
    работы в Health IT и является активными членами организации HL7, постарается дать вам правильный старт.
    Мы кратко познакомимся с актуальными стандартами обмена медицинской информацией и их историей.
    Основная часть тренинга будет посвященна молодому, но очень перспективному стандарту FHIR,
    который включил в себя основные достижения предшествующих стандартов и исключил многие их недостатки.
  plan: fhir-intro.ru.md
  tags:
    - FHIR
    - HL7
    - Standards
- id: fhirbase
  title:
    en: Fhirbase anatomy
    ru: Анатомия fhirbase
  abstract:
    ru: >
      Тренинг по архитектуре и использованию открытой медицинской базы Fhirbase в разработке
      решений для здравоохранения
    en: Training about  architecture and usage of opensource medical database - FHIRbase
  desc:
    ru: >
      Fhirbase - это база данных созданная на основе стандарта FHIR и открытой реляционной базы
      PostgreSQL для хранения медицинской информации. Двухдневный тренинг от разработчиков этой базы,
      позволит вам научиться ее использовать и разобраться в том как она устроенна. Тренинг не подразумевает
      глубоких познаний в PostgreSQL и основные его возможности будут объясненны по ходу тренинга.
      Интерфейс fhirbase прост, но более глубокое понимание ее устройства даст
      вам возможность воспользоваться всей мощью PostgreSQL и эффективно расширять fhirbase под ваши
      конкретные нужды. Так же мы затронем вопросы практической эксплуатации fhirbase в боевых условиях,
      такие как настройка производительности, репликация и бэкапы.
    en: >
      ?????
  img: /imgs/fhirbase.svg
  plan: fhirbase.ru.md
  tags:
    - FHIR
    - fhirbase
    - PostgreSQL
- id: devops
  title:
    ru: Непрерываная поставка
    en: Continuous Delivery
  img: /imgs/devops.svg
  tags:
    - DevOps
    - ContinuousDelivery
    - LEAN
  abstract:
    ru: Двухдневный тренинг по подходам и инструментам построения непрерывного цикла поставки
    en: Two days training about Continuous Delivery....
  desc: >
    Современный софт стремительно превращается из коробочного продукта в
    сервис. Пользователи хотят получать доступ к новым функциям
    как можно быстрее. Цикл поставки у лидеров рынка сократился до дней
    или даже часов. Поэтому, чтобы выжить, мы должны пересмотреть и перестроить
    процесс производства информационных систем коренным образом, и это непростой
    вызов. Двухдневный тренинг от HealthSamurai возможно станет первым шагом в этом
    направлении. Мы познакомимся с движением DevOps и философией бережливого производства (LEAN).
    Попробуем хорошие практики и инструменты позволяющие выстроить эффективную
    и надежную линию непрерывного производства (Continuous Delivery Pipeline)
  plan: devops.ru.md
